pipeline {
    agent any

    tools {
        terraform 'terraform'
    }

    stages {
        stage('Checkout SCM') {
         steps{
   
            sh  'git clone https://github.com/Ellawangari/Terraform_Projects.git'
            
          
         }
        }
        stage ("terraform init") {
            steps {
                
                sh 'terraform init'
            }
        }
        stage ("terraform fmt") {
            steps {
                sh 'terraform fmt'
            }
        }
        stage ("terraform validate") {
            steps {
                sh 'terraform validate'
            }
        }
        stage ("terrafrom plan") {
            steps {
                sh 'terraform plan -out=tfplan.out '
            }
        }
       stage("terraform show") {
           steps{
            sh'terraform show -json tfplan.out'
           }

       }

        stage ("terraform apply") {
            steps {
                sh 'terraform apply --auto-approve'
            }
        }
    }
}