pipeline {
    agent any

    tools {
        terraform 'terraform'
    }

    stages {
        stage('Checkout SCM') {
         steps{
            git branch: 'terraform-Jenkins', url: 'https://github.com/Ellawangari/Terraform-Projects.git'
         }
        }
        stage ("terraform init") {
            steps {
                sh 'terraform init'
            }
        }
        stage ("terraform fmt") {
            steps {
                sh 'terraform fmt'
            }
        }
        stage ("terraform validate") {
            steps {
                sh 'terraform validate'
            }
        }
        stage ("terrafrom plan") {
            steps {
                sh 'terraform plan '
            }
        }
        stage ("terraform apply") {
            steps {
                sh 'terraform apply --auto-approve'
            }
        }
    }
}